### ISSUE TITLE
error: incompatible types for redefinition of 'GetVersion' ...

### ISSUE THREAD

**Issue by Anivie** [Larpon/jni#13]
**OS:**
Windows 11
**V version**
V 0.3.2 bf0c8a0
**What did you do?**
Compile in code:
```vlang
module cat

import jni

#flag windows -I $env('JAVA_HOME')\include
#flag windows -I $env('JAVA_HOME')\include\win32
#flag windows -I $env('JAVA_HOME')\include\win32\bridge

// jni_on_load is called by the JavaVM upon setup
[export: 'JNI_OnLoad']
fn jni_on_load(vm &jni.JavaVM, reserved voidptr) int {
	println(@FN + ' called')
	jni.set_java_vm(vm)
	return int(jni.Version.v1_6)
}

// get_string_from_v returns a string obtained from Java via a static method call
[export: 'JNICALL Java_io_v_V_getStringFromV']
fn get_string_from_v(env &jni.Env, thiz jni.JavaObject) jni.JavaString {
	// Obtain the string "Hello from Java!" from the Java class...
	call_result := jni.call_static_method(env, 'io.v.V.getStringFromJava() string')
	// Cast the value of the call result to a v 'string'...
	string_from_java := call_result.result as string
	println(@MOD + '.' + @FN + ' string from Java "${string_from_java}"')
	// Return a Java 'String' to the caller - replacing 'Java' with 'V'...
	return jni.jstring(env, string_from_java.replace('Java', 'V'))
}
```
**What did you expect to see?**
C:/Users/anivi/AppData/Local/Temp/v_0/main.dll.16824221152644964963.tmp.so.c:494: warning: WINVER redefined
In file included from C:/Users/anivi/AppData/Local/Temp/v_0/main.dll.16824221152644964963.tmp.so.c:783:
D:/V_Repository/jni/c/jni_wrapper.h:8: error: incompatible types for redefinition of 'GetVersion'

**Comment by larpon** [comment]
Might be similar to the issues we had with `windows.h`
https://github.com/irishgreencitrus/raylib.v/issues/1
https://github.com/irishgreencitrus/raylib.v/commit/1b84649
https://github.com/vlang/v/pull/15456

**Comment by Anivie** [comment]
> Might be similar to the issues we had with `windows.h` [irishgreencitrus/raylib.v#1](https://github.com/irishgreencitrus/raylib.v/issues/1) [irishgreencitrus/raylib.v@1b84649](https://github.com/irishgreencitrus/raylib.v/commit/1b84649) [vlang/v#15456](https://github.com/vlang/v/pull/15456)

So,how can I fix it?

**Comment by larpon** [comment]
I'm not 100% sure, since I'm no expert in fixing colliding symbol names and Windows is known to cause such headaches. There's no easy fix to it since Windows has chosen to use very common names for their functions in their win32 API headers.

My initial thought is that the function [GetVersion](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversion) is the one colliding with JNI's `GetVersion`. If you don't need the Java version simply comment it out of the source [here](https://github.com/Larpon/jni/blob/899872e8ecfb3d9e25e8f2f29eaa97204aa42c1a/c/jni_wrapper.h#L8-L10) and [here](https://github.com/Larpon/jni/blob/899872e8ecfb3d9e25e8f2f29eaa97204aa42c1a/jni.c.v#L151-L154). If you do need it you'll need to find a way to exclude the function in `<windows.h>` (not sure how possible it is) it's possible, to some extend, to exclude certain functions, like it's done [here](https://github.com/irishgreencitrus/raylib.v/commit/1b84649#diff-e742c391ade1958d3cde0e1120b685ccd76231bc9977314877e3ae099b32303bR1-R54) before including `<windows.h>`. If you go down that road make sure you do it in a `pre.h` file you include in your V code [via `#preinclude`](https://github.com/irishgreencitrus/raylib.v/commit/1b84649#diff-de6afcba2f5ddd497d7c849887e6c2abb2601f39b6662427911e8f5ddf129366R3).
